import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Playlist } from '../components/Playlist/playlist'
import { Song } from '../components/Song/song'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Spotifai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Playlist/>
    </div>
  )
}

export default Home
